POST https://{{host}}/{{token}}
Content-Type: application/json

{
  "message": {
    "message_id": 123
  }
}

###
POST https://{{host}}
Content-Type: application/json

{
  "message": {
    "message_id": 123
  }
}

###